"""Synthetic M&A deal dataset - 30 realistic deals including Reliance-Viacom18."""
from datetime import datetime, timedelta, timezone

# Each deal contains: id, target_ticker, target_name, acquirer_ticker, acquirer_name,
# announce_date, expected_close, deal_value_b (USD billions), payment, sector,
# acquirer_country, target_country, hhi_change, target_price_pre, offer_price, current_price,
# regulators (list), status, governance_resistance(0-1), management_resistance(0-1),
# financing_certainty (0-1), competing_bidder_prob(0-1), activist_intensity(0-1),
# acquirer_dte (debt/ebitda), interest_coverage, prior_deal_success_rate,
# milestones (list of {label,date,status}), narrative_blurb

DEALS = [
    {
        "id": "MSFT-ATVI", "target_ticker": "ATVI", "target_name": "Activision Blizzard",
        "acquirer_ticker": "MSFT", "acquirer_name": "Microsoft", "announce_date": "2022-01-18",
        "expected_close": "2023-10-13", "deal_value_b": 68.7, "payment": "Cash", "sector": "Technology / Gaming",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 380,
        "target_price_pre": 65.39, "offer_price": 95.00, "current_price": 94.42,
        "regulators": ["FTC","CMA","EC","SAMR"], "status": "Closed",
        "governance_resistance": 0.15, "management_resistance": 0.20, "financing_certainty": 0.95,
        "competing_bidder_prob": 0.05, "activist_intensity": 0.35,
        "acquirer_dte": 0.7, "interest_coverage": 24.0, "prior_deal_success_rate": 0.78,
    },
    {
        "id": "AVGO-VMW", "target_ticker": "VMW", "target_name": "VMware",
        "acquirer_ticker": "AVGO", "acquirer_name": "Broadcom", "announce_date": "2022-05-26",
        "expected_close": "2023-11-22", "deal_value_b": 61.0, "payment": "Cash+Stock", "sector": "Technology / Enterprise SW",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 220,
        "target_price_pre": 95.71, "offer_price": 142.50, "current_price": 141.10,
        "regulators": ["FTC","CMA","EC","SAMR"], "status": "Closed",
        "governance_resistance": 0.20, "management_resistance": 0.10, "financing_certainty": 0.92,
        "competing_bidder_prob": 0.04, "activist_intensity": 0.30,
        "acquirer_dte": 3.2, "interest_coverage": 8.0, "prior_deal_success_rate": 0.82,
    },
    {
        "id": "RIL-VIACOM18", "target_ticker": "VIACOM18", "target_name": "Viacom18 (Disney Star + Viacom18)",
        "acquirer_ticker": "RELIANCE", "acquirer_name": "Reliance Industries (Jio)",
        "announce_date": "2024-02-28", "expected_close": "2024-11-14", "deal_value_b": 8.5,
        "payment": "Stock+Cash", "sector": "Media & Entertainment",
        "acquirer_country": "IN", "target_country": "IN/US", "hhi_change": 540,
        "target_price_pre": 1.00, "offer_price": 1.15, "current_price": 1.14,
        "regulators": ["CCI","NCLT","SEBI"], "status": "Closed",
        "governance_resistance": 0.10, "management_resistance": 0.05, "financing_certainty": 0.96,
        "competing_bidder_prob": 0.02, "activist_intensity": 0.10,
        "acquirer_dte": 1.6, "interest_coverage": 12.0, "prior_deal_success_rate": 0.88,
    },
    {
        "id": "CVX-HES", "target_ticker": "HES", "target_name": "Hess Corporation",
        "acquirer_ticker": "CVX", "acquirer_name": "Chevron", "announce_date": "2023-10-23",
        "expected_close": "2025-Q2", "deal_value_b": 53.0, "payment": "Stock", "sector": "Energy / Oil & Gas",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 95,
        "target_price_pre": 163.10, "offer_price": 171.00, "current_price": 154.75,
        "regulators": ["FTC","ExxonArbitration"], "status": "Pending",
        "governance_resistance": 0.30, "management_resistance": 0.15, "financing_certainty": 0.85,
        "competing_bidder_prob": 0.10, "activist_intensity": 0.25,
        "acquirer_dte": 1.1, "interest_coverage": 18.0, "prior_deal_success_rate": 0.72,
    },
    {
        "id": "XOM-PXD", "target_ticker": "PXD", "target_name": "Pioneer Natural Resources",
        "acquirer_ticker": "XOM", "acquirer_name": "ExxonMobil", "announce_date": "2023-10-11",
        "expected_close": "2024-05-03", "deal_value_b": 64.5, "payment": "Stock", "sector": "Energy / Oil & Gas",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 140,
        "target_price_pre": 214.00, "offer_price": 253.00, "current_price": 251.40,
        "regulators": ["FTC"], "status": "Closed",
        "governance_resistance": 0.18, "management_resistance": 0.10, "financing_certainty": 0.95,
        "competing_bidder_prob": 0.03, "activist_intensity": 0.15,
        "acquirer_dte": 0.6, "interest_coverage": 30.0, "prior_deal_success_rate": 0.85,
    },
    {
        "id": "AMAT-KMTUY", "target_ticker": "KMTUY", "target_name": "Kokusai Electric",
        "acquirer_ticker": "AMAT", "acquirer_name": "Applied Materials", "announce_date": "2024-09-15",
        "expected_close": "2025-Q4", "deal_value_b": 9.0, "payment": "Cash", "sector": "Semiconductors",
        "acquirer_country": "US", "target_country": "JP", "hhi_change": 290,
        "target_price_pre": 18.40, "offer_price": 23.00, "current_price": 19.85,
        "regulators": ["SAMR","JFTC","CFIUS","EC"], "status": "Pending",
        "governance_resistance": 0.25, "management_resistance": 0.20, "financing_certainty": 0.90,
        "competing_bidder_prob": 0.07, "activist_intensity": 0.20,
        "acquirer_dte": 0.4, "interest_coverage": 42.0, "prior_deal_success_rate": 0.62,
    },
    {
        "id": "CI-HUM", "target_ticker": "HUM", "target_name": "Humana",
        "acquirer_ticker": "CI", "acquirer_name": "Cigna", "announce_date": "2023-11-29",
        "expected_close": "2024-Q4", "deal_value_b": 65.0, "payment": "Cash+Stock", "sector": "Healthcare / Insurance",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 720,
        "target_price_pre": 510.00, "offer_price": 0, "current_price": 358.00,
        "regulators": ["FTC","DOJ"], "status": "Terminated",
        "governance_resistance": 0.55, "management_resistance": 0.45, "financing_certainty": 0.70,
        "competing_bidder_prob": 0.08, "activist_intensity": 0.40,
        "acquirer_dte": 2.5, "interest_coverage": 9.0, "prior_deal_success_rate": 0.55,
    },
    {
        "id": "JBHT-KNX", "target_ticker": "KNX", "target_name": "Knight-Swift Transportation",
        "acquirer_ticker": "JBHT", "acquirer_name": "J.B. Hunt", "announce_date": "2025-06-10",
        "expected_close": "2026-Q2", "deal_value_b": 18.5, "payment": "Stock", "sector": "Transportation",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 410,
        "target_price_pre": 48.20, "offer_price": 58.00, "current_price": 54.10,
        "regulators": ["DOJ","STB"], "status": "Pending",
        "governance_resistance": 0.30, "management_resistance": 0.25, "financing_certainty": 0.80,
        "competing_bidder_prob": 0.12, "activist_intensity": 0.30,
        "acquirer_dte": 1.4, "interest_coverage": 14.0, "prior_deal_success_rate": 0.68,
    },
    {
        "id": "NVDA-ARM", "target_ticker": "ARM", "target_name": "Arm Holdings",
        "acquirer_ticker": "NVDA", "acquirer_name": "NVIDIA", "announce_date": "2020-09-13",
        "expected_close": "2022-02-08", "deal_value_b": 40.0, "payment": "Cash+Stock", "sector": "Semiconductors",
        "acquirer_country": "US", "target_country": "GB", "hhi_change": 880,
        "target_price_pre": 1.00, "offer_price": 0, "current_price": 0,
        "regulators": ["FTC","CMA","EC","SAMR"], "status": "Terminated",
        "governance_resistance": 0.40, "management_resistance": 0.30, "financing_certainty": 0.85,
        "competing_bidder_prob": 0.10, "activist_intensity": 0.45,
        "acquirer_dte": 0.5, "interest_coverage": 50.0, "prior_deal_success_rate": 0.60,
    },
    {
        "id": "BHP-AAL", "target_ticker": "AAL.L", "target_name": "Anglo American",
        "acquirer_ticker": "BHP", "acquirer_name": "BHP Group", "announce_date": "2024-04-25",
        "expected_close": "2025-Q1", "deal_value_b": 49.0, "payment": "Stock", "sector": "Mining / Metals",
        "acquirer_country": "AU", "target_country": "GB/ZA", "hhi_change": 510,
        "target_price_pre": 24.20, "offer_price": 31.10, "current_price": 0,
        "regulators": ["CMA","SACC","FIRB"], "status": "Withdrawn",
        "governance_resistance": 0.65, "management_resistance": 0.70, "financing_certainty": 0.75,
        "competing_bidder_prob": 0.18, "activist_intensity": 0.50,
        "acquirer_dte": 0.9, "interest_coverage": 22.0, "prior_deal_success_rate": 0.58,
    },
    {
        "id": "ADBE-FIGMA", "target_ticker": "FIGMA", "target_name": "Figma",
        "acquirer_ticker": "ADBE", "acquirer_name": "Adobe", "announce_date": "2022-09-15",
        "expected_close": "2023-12-17", "deal_value_b": 20.0, "payment": "Cash+Stock", "sector": "Technology / Design SW",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 1100,
        "target_price_pre": 1.00, "offer_price": 0, "current_price": 0,
        "regulators": ["FTC","CMA","EC"], "status": "Terminated",
        "governance_resistance": 0.20, "management_resistance": 0.10, "financing_certainty": 0.95,
        "competing_bidder_prob": 0.03, "activist_intensity": 0.15,
        "acquirer_dte": 0.3, "interest_coverage": 60.0, "prior_deal_success_rate": 0.66,
    },
    {
        "id": "SU-USS", "target_ticker": "USS", "target_name": "U.S. Steel",
        "acquirer_ticker": "5401.T", "acquirer_name": "Nippon Steel", "announce_date": "2023-12-18",
        "expected_close": "2025-Q1", "deal_value_b": 14.9, "payment": "Cash", "sector": "Steel / Industrials",
        "acquirer_country": "JP", "target_country": "US", "hhi_change": 180,
        "target_price_pre": 39.30, "offer_price": 55.00, "current_price": 38.20,
        "regulators": ["CFIUS","DOJ"], "status": "Pending",
        "governance_resistance": 0.45, "management_resistance": 0.30, "financing_certainty": 0.85,
        "competing_bidder_prob": 0.20, "activist_intensity": 0.60,
        "acquirer_dte": 1.8, "interest_coverage": 11.0, "prior_deal_success_rate": 0.70,
    },
    {
        "id": "PFE-SGEN", "target_ticker": "SGEN", "target_name": "Seagen",
        "acquirer_ticker": "PFE", "acquirer_name": "Pfizer", "announce_date": "2023-03-13",
        "expected_close": "2023-12-14", "deal_value_b": 43.0, "payment": "Cash", "sector": "Pharma / Biotech",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 95,
        "target_price_pre": 172.61, "offer_price": 229.00, "current_price": 228.75,
        "regulators": ["FTC","EC"], "status": "Closed",
        "governance_resistance": 0.12, "management_resistance": 0.08, "financing_certainty": 0.93,
        "competing_bidder_prob": 0.05, "activist_intensity": 0.20,
        "acquirer_dte": 2.2, "interest_coverage": 16.0, "prior_deal_success_rate": 0.80,
    },
    {
        "id": "AMZN-IRBT", "target_ticker": "IRBT", "target_name": "iRobot",
        "acquirer_ticker": "AMZN", "acquirer_name": "Amazon", "announce_date": "2022-08-05",
        "expected_close": "2024-01-29", "deal_value_b": 1.7, "payment": "Cash", "sector": "Consumer Electronics",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 240,
        "target_price_pre": 49.99, "offer_price": 0, "current_price": 0,
        "regulators": ["EC","CMA","FTC"], "status": "Terminated",
        "governance_resistance": 0.18, "management_resistance": 0.10, "financing_certainty": 0.95,
        "competing_bidder_prob": 0.04, "activist_intensity": 0.20,
        "acquirer_dte": 0.5, "interest_coverage": 28.0, "prior_deal_success_rate": 0.71,
    },
    {
        "id": "TD-FHN", "target_ticker": "FHN", "target_name": "First Horizon",
        "acquirer_ticker": "TD", "acquirer_name": "TD Bank", "announce_date": "2022-02-28",
        "expected_close": "2023-05-04", "deal_value_b": 13.4, "payment": "Cash", "sector": "Financials / Banking",
        "acquirer_country": "CA", "target_country": "US", "hhi_change": 80,
        "target_price_pre": 23.81, "offer_price": 0, "current_price": 0,
        "regulators": ["OCC","FRB","OSFI"], "status": "Terminated",
        "governance_resistance": 0.15, "management_resistance": 0.10, "financing_certainty": 0.92,
        "competing_bidder_prob": 0.04, "activist_intensity": 0.25,
        "acquirer_dte": 1.0, "interest_coverage": 10.0, "prior_deal_success_rate": 0.76,
    },
    {
        "id": "KR-ACI", "target_ticker": "ACI", "target_name": "Albertsons",
        "acquirer_ticker": "KR", "acquirer_name": "Kroger", "announce_date": "2022-10-14",
        "expected_close": "2024-Q1", "deal_value_b": 24.6, "payment": "Cash", "sector": "Consumer / Grocery",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 650,
        "target_price_pre": 26.21, "offer_price": 0, "current_price": 0,
        "regulators": ["FTC"], "status": "Terminated",
        "governance_resistance": 0.30, "management_resistance": 0.20, "financing_certainty": 0.88,
        "competing_bidder_prob": 0.05, "activist_intensity": 0.35,
        "acquirer_dte": 1.7, "interest_coverage": 8.0, "prior_deal_success_rate": 0.65,
    },
    {
        "id": "CSCO-SPLK", "target_ticker": "SPLK", "target_name": "Splunk",
        "acquirer_ticker": "CSCO", "acquirer_name": "Cisco", "announce_date": "2023-09-21",
        "expected_close": "2024-03-18", "deal_value_b": 28.0, "payment": "Cash", "sector": "Technology / Cybersecurity",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 140,
        "target_price_pre": 119.00, "offer_price": 157.00, "current_price": 156.80,
        "regulators": ["FTC","EC"], "status": "Closed",
        "governance_resistance": 0.15, "management_resistance": 0.10, "financing_certainty": 0.95,
        "competing_bidder_prob": 0.04, "activist_intensity": 0.15,
        "acquirer_dte": 1.2, "interest_coverage": 22.0, "prior_deal_success_rate": 0.83,
    },
    {
        "id": "MRK-PRME", "target_ticker": "PRME", "target_name": "Prometheus Biosciences",
        "acquirer_ticker": "MRK", "acquirer_name": "Merck", "announce_date": "2023-04-16",
        "expected_close": "2023-06-16", "deal_value_b": 10.8, "payment": "Cash", "sector": "Pharma / Biotech",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 110,
        "target_price_pre": 113.65, "offer_price": 200.00, "current_price": 199.80,
        "regulators": ["FTC"], "status": "Closed",
        "governance_resistance": 0.10, "management_resistance": 0.05, "financing_certainty": 0.97,
        "competing_bidder_prob": 0.03, "activist_intensity": 0.10,
        "acquirer_dte": 1.5, "interest_coverage": 20.0, "prior_deal_success_rate": 0.84,
    },
    {
        "id": "TSN-ADM", "target_ticker": "ADM", "target_name": "Archer Daniels (Hypothetical)",
        "acquirer_ticker": "TSN", "acquirer_name": "Tyson Foods", "announce_date": "2025-08-12",
        "expected_close": "2026-Q3", "deal_value_b": 38.0, "payment": "Cash+Stock", "sector": "Consumer / Food Processing",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 580,
        "target_price_pre": 56.20, "offer_price": 71.00, "current_price": 64.30,
        "regulators": ["DOJ","FTC"], "status": "Pending",
        "governance_resistance": 0.35, "management_resistance": 0.40, "financing_certainty": 0.78,
        "competing_bidder_prob": 0.12, "activist_intensity": 0.45,
        "acquirer_dte": 2.1, "interest_coverage": 9.0, "prior_deal_success_rate": 0.63,
    },
    {
        "id": "EL-FRES", "target_ticker": "FRES", "target_name": "Frontier Resources",
        "acquirer_ticker": "EL", "acquirer_name": "EnerLux", "announce_date": "2025-09-30",
        "expected_close": "2026-Q4", "deal_value_b": 7.2, "payment": "Stock", "sector": "Energy / Renewables",
        "acquirer_country": "DE", "target_country": "BR", "hhi_change": 210,
        "target_price_pre": 14.20, "offer_price": 17.80, "current_price": 16.40,
        "regulators": ["EC","CADE","CFIUS"], "status": "Pending",
        "governance_resistance": 0.25, "management_resistance": 0.20, "financing_certainty": 0.82,
        "competing_bidder_prob": 0.15, "activist_intensity": 0.20,
        "acquirer_dte": 1.5, "interest_coverage": 14.0, "prior_deal_success_rate": 0.71,
    },
    {
        "id": "GOOG-WIZ", "target_ticker": "WIZ", "target_name": "Wiz",
        "acquirer_ticker": "GOOG", "acquirer_name": "Alphabet (Google Cloud)", "announce_date": "2025-03-18",
        "expected_close": "2026-Q1", "deal_value_b": 32.0, "payment": "Cash", "sector": "Technology / Cybersecurity",
        "acquirer_country": "US", "target_country": "IL/US", "hhi_change": 310,
        "target_price_pre": 1.00, "offer_price": 1.30, "current_price": 1.24,
        "regulators": ["FTC","EC","CMA"], "status": "Pending",
        "governance_resistance": 0.18, "management_resistance": 0.10, "financing_certainty": 0.98,
        "competing_bidder_prob": 0.05, "activist_intensity": 0.20,
        "acquirer_dte": 0.2, "interest_coverage": 80.0, "prior_deal_success_rate": 0.74,
    },
    {
        "id": "CAH-OPTUMRX", "target_ticker": "OPRX", "target_name": "OptumRx Specialty Unit (Carve-out)",
        "acquirer_ticker": "CAH", "acquirer_name": "Cardinal Health", "announce_date": "2025-11-04",
        "expected_close": "2026-Q3", "deal_value_b": 9.5, "payment": "Cash", "sector": "Healthcare / Pharmacy",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 340,
        "target_price_pre": 1.00, "offer_price": 1.10, "current_price": 1.05,
        "regulators": ["FTC","DOJ"], "status": "Pending",
        "governance_resistance": 0.25, "management_resistance": 0.18, "financing_certainty": 0.88,
        "competing_bidder_prob": 0.10, "activist_intensity": 0.25,
        "acquirer_dte": 1.9, "interest_coverage": 11.0, "prior_deal_success_rate": 0.72,
    },
    {
        "id": "GS-PYPL", "target_ticker": "PYPL", "target_name": "PayPal Holdings (Hypothetical Bid)",
        "acquirer_ticker": "GS", "acquirer_name": "Goldman Consortium", "announce_date": "2025-10-20",
        "expected_close": "2026-Q4", "deal_value_b": 78.0, "payment": "Cash", "sector": "Financials / Fintech",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 420,
        "target_price_pre": 62.10, "offer_price": 82.00, "current_price": 71.40,
        "regulators": ["FTC","FRB","EC","CFPB"], "status": "Pending",
        "governance_resistance": 0.45, "management_resistance": 0.50, "financing_certainty": 0.72,
        "competing_bidder_prob": 0.30, "activist_intensity": 0.55,
        "acquirer_dte": 2.0, "interest_coverage": 12.0, "prior_deal_success_rate": 0.58,
    },
    {
        "id": "TSMC-GFS", "target_ticker": "GFS", "target_name": "GlobalFoundries",
        "acquirer_ticker": "TSM", "acquirer_name": "TSMC", "announce_date": "2025-07-09",
        "expected_close": "2026-Q4", "deal_value_b": 42.5, "payment": "Cash", "sector": "Semiconductors",
        "acquirer_country": "TW", "target_country": "US", "hhi_change": 760,
        "target_price_pre": 41.00, "offer_price": 56.00, "current_price": 46.10,
        "regulators": ["CFIUS","SAMR","EC","FTC"], "status": "Pending",
        "governance_resistance": 0.50, "management_resistance": 0.35, "financing_certainty": 0.83,
        "competing_bidder_prob": 0.15, "activist_intensity": 0.40,
        "acquirer_dte": 0.4, "interest_coverage": 45.0, "prior_deal_success_rate": 0.65,
    },
    {
        "id": "BLK-PRESQ", "target_ticker": "PRESQ", "target_name": "Preqin",
        "acquirer_ticker": "BLK", "acquirer_name": "BlackRock", "announce_date": "2024-07-01",
        "expected_close": "2024-Q4", "deal_value_b": 3.2, "payment": "Cash", "sector": "Financials / Data",
        "acquirer_country": "US", "target_country": "GB", "hhi_change": 220,
        "target_price_pre": 1.00, "offer_price": 1.10, "current_price": 1.095,
        "regulators": ["CMA","FTC"], "status": "Closed",
        "governance_resistance": 0.10, "management_resistance": 0.05, "financing_certainty": 0.99,
        "competing_bidder_prob": 0.05, "activist_intensity": 0.10,
        "acquirer_dte": 1.0, "interest_coverage": 28.0, "prior_deal_success_rate": 0.87,
    },
    {
        "id": "DIS-FOX", "target_ticker": "FOXA", "target_name": "21st Century Fox",
        "acquirer_ticker": "DIS", "acquirer_name": "Walt Disney Co.", "announce_date": "2017-12-14",
        "expected_close": "2019-03-20", "deal_value_b": 71.3, "payment": "Stock+Cash", "sector": "Media & Entertainment",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 480,
        "target_price_pre": 32.78, "offer_price": 38.00, "current_price": 0,
        "regulators": ["DOJ","EC","CCI","SAMR"], "status": "Closed",
        "governance_resistance": 0.20, "management_resistance": 0.10, "financing_certainty": 0.94,
        "competing_bidder_prob": 0.40, "activist_intensity": 0.30,
        "acquirer_dte": 1.5, "interest_coverage": 15.0, "prior_deal_success_rate": 0.82,
    },
    {
        "id": "TM-HMC", "target_ticker": "HMC", "target_name": "Honda Motor (Partial Stake JV)",
        "acquirer_ticker": "TM", "acquirer_name": "Toyota Motor", "announce_date": "2026-01-15",
        "expected_close": "2027-Q1", "deal_value_b": 22.0, "payment": "Cash+Stock", "sector": "Automotive",
        "acquirer_country": "JP", "target_country": "JP", "hhi_change": 620,
        "target_price_pre": 28.50, "offer_price": 34.00, "current_price": 30.10,
        "regulators": ["JFTC","EC","SAMR","FTC"], "status": "Pending",
        "governance_resistance": 0.40, "management_resistance": 0.45, "financing_certainty": 0.80,
        "competing_bidder_prob": 0.10, "activist_intensity": 0.30,
        "acquirer_dte": 0.8, "interest_coverage": 30.0, "prior_deal_success_rate": 0.75,
    },
    {
        "id": "VRTX-ALPN", "target_ticker": "ALPN", "target_name": "Alpine Immune Sciences",
        "acquirer_ticker": "VRTX", "acquirer_name": "Vertex Pharmaceuticals", "announce_date": "2024-04-10",
        "expected_close": "2024-07-09", "deal_value_b": 4.9, "payment": "Cash", "sector": "Pharma / Biotech",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 60,
        "target_price_pre": 39.61, "offer_price": 65.00, "current_price": 64.95,
        "regulators": ["FTC"], "status": "Closed",
        "governance_resistance": 0.08, "management_resistance": 0.05, "financing_certainty": 0.98,
        "competing_bidder_prob": 0.04, "activist_intensity": 0.10,
        "acquirer_dte": 0.5, "interest_coverage": 55.0, "prior_deal_success_rate": 0.86,
    },
    {
        "id": "VLT-NTNX", "target_ticker": "NTNX", "target_name": "Nutanix",
        "acquirer_ticker": "VLT", "acquirer_name": "Vault Technologies", "announce_date": "2025-12-09",
        "expected_close": "2026-Q4", "deal_value_b": 16.4, "payment": "Cash", "sector": "Technology / Cloud",
        "acquirer_country": "US", "target_country": "US", "hhi_change": 290,
        "target_price_pre": 62.10, "offer_price": 82.50, "current_price": 76.20,
        "regulators": ["FTC","EC","CMA"], "status": "Pending",
        "governance_resistance": 0.22, "management_resistance": 0.18, "financing_certainty": 0.85,
        "competing_bidder_prob": 0.12, "activist_intensity": 0.25,
        "acquirer_dte": 1.6, "interest_coverage": 13.0, "prior_deal_success_rate": 0.74,
    },
    {
        "id": "SAN-BLK-EU", "target_ticker": "SAN-BLK-EU", "target_name": "BlueKite Energy Networks",
        "acquirer_ticker": "SAN", "acquirer_name": "Santander Infrastructure",
        "announce_date": "2026-01-22", "expected_close": "2026-Q4", "deal_value_b": 11.8,
        "payment": "Cash", "sector": "Energy / Utilities",
        "acquirer_country": "ES", "target_country": "PL", "hhi_change": 280,
        "target_price_pre": 1.00, "offer_price": 1.18, "current_price": 1.10,
        "regulators": ["EC","UOKiK","CFIUS-EU"], "status": "Pending",
        "governance_resistance": 0.28, "management_resistance": 0.22, "financing_certainty": 0.86,
        "competing_bidder_prob": 0.10, "activist_intensity": 0.20,
        "acquirer_dte": 2.0, "interest_coverage": 9.0, "prior_deal_success_rate": 0.69,
    },
]


def build_milestones(deal):
    """Generate lifecycle milestone events for a deal."""
    try:
        ann = datetime.strptime(deal["announce_date"], "%Y-%m-%d").replace(tzinfo=timezone.utc)
    except Exception:
        ann = datetime.now(timezone.utc) - timedelta(days=180)
    base = [
        ("Deal Announcement", ann, "complete"),
        ("HSR Notification Filed", ann + timedelta(days=15), "complete"),
        ("Proxy Statement Filed", ann + timedelta(days=45), "complete"),
        ("Regulatory Phase I Review", ann + timedelta(days=90),
            "complete" if deal["status"] in ("Closed","Terminated","Withdrawn") else "in-progress"),
        ("Shareholder Vote", ann + timedelta(days=150),
            "complete" if deal["status"] == "Closed" else "pending"),
        ("Regulatory Final Approval", ann + timedelta(days=240),
            "complete" if deal["status"] == "Closed" else
            ("blocked" if deal["status"] in ("Terminated","Withdrawn") else "pending")),
        ("Deal Close", ann + timedelta(days=300),
            "complete" if deal["status"] == "Closed" else
            ("blocked" if deal["status"] in ("Terminated","Withdrawn") else "pending")),
    ]
    return [{"label": l, "date": d.isoformat(), "status": s} for l, d, s in base]


def get_seed_deals():
    enriched = []
    for d in DEALS:
        d2 = dict(d)
        d2["milestones"] = build_milestones(d)
        enriched.append(d2)
    return enriched
