// Test ID constants used across the app
export const IDS = {
  topBar: "top-bar",
  navDashboard: "nav-dashboard",
  navSimulator: "nav-simulator",
  navAbout: "nav-about",
  dealUniverseTable: "deal-universe-table",
  dealRow: (id) => `deal-row-${id}`,
  filterStatus: "filter-status",
  filterSector: "filter-sector",
  filterSearch: "filter-search",
  portfolioPanel: "portfolio-panel",
  liveTicker: "live-ticker",
  dealDetailPage: "deal-detail-page",
  dealHealthGauge: "deal-health-gauge",
  spreadChart: "spread-chart",
  forceGraph: "force-graph",
  regPanel: "reg-panel",
  votePanel: "vote-panel",
  geoPanel: "geo-panel",
  fallbackPanel: "fallback-panel",
  scenarioPanel: "scenario-panel",
  llmAnalyzeBtn: "llm-analyze-btn",
  llmOutput: "llm-output",
  scenarioRun: "scenario-run-btn",
};
